
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-05
owner: ucsb-cs156-s26
repo_name: team01-s26-05
pull_requests: [{"author":{"id":"U_kgDOCbzrWw","is_bot":false,"login":"katskt","name":"Katie"},"headRefName":"kp-put-for-rec-req","number":75,"title":"Add PUT (edit) endpoint for a single record in RecommendationRequest table, added tests for PUT endpoint","url":"https://github.com/ucsb-cs156-s26/team01-s26-05/pull/75"},{"author":{"id":"U_kgDOCx52uQ","is_bot":false,"login":"alexiasargsyan","name":"Alexia Sargsyan"},"headRefName":"UCSBOrganizationController-DELETE-alexiasargsyan","number":74,"title":"feat: add DELETE endpoint for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-05/pull/74"},{"author":{"id":"U_kgDOCx52uQ","is_bot":false,"login":"alexiasargsyan","name":"Alexia Sargsyan"},"headRefName":"UCSBOrganizationController-PUT-alexiasargsyan","number":73,"title":"feat: add PUT endpoint for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team01-s26-05/pull/73"}]
